### ISSUE TITLE
Shu yerdagi linkni ya'ni header-login-linkni (element emas) divni block qilin (a ni)  element qilganingiz yaxshi.

### ISSUE THREAD

**Issue by JumabaevZiyodilla** [SayramovAzizbek/Azizbek-Bookmark#6]
![Screenshot_2](https://user-images.githubusercontent.com/107662716/176837238-f99850ea-b4ae-46bb-8af3-a3c5359c423a.png)

**Comment by SayramovAzizbek** [comment]
buni BEM bo'yicha block qilib olgan edim, lekin sizni variantingiz ham yomon emas
