### ISSUE TITLE
asalomalekum mr:44pxga ozgartirsak zor ish bolar edi

### ISSUE THREAD

**Issue by Bunyod1202** [SayramovAzizbek/Azizbek-Bookmark#7]
![image](https://user-images.githubusercontent.com/84246289/176986938-4e990c8a-2fbf-4a92-accb-c5ceee83e531.png)

**Comment by SayramovAzizbek** [comment]
figmada hstolik bo'lgan hammasini margini har hil berilgan, shu uchun o'rtachasini olib qo'yilgan
